// generated by stringer -type=cipPacketType; DO NOT EDIT

package main

import "fmt"

const _cipPacketType_name = "unk00unk01unk02unk03unk04PacketSetunk06unk07unk08unk09unk0aunk0bunk0cPacketEchoRequestPacketEchoResponseunk0funk10unk11unk12unk13unk14unk15unk16unk17unk18unk19unk1aunk1bunk1cunk1dunk1eunk1f"

var _cipPacketType_index = [...]uint8{0, 5, 10, 15, 20, 25, 34, 39, 44, 49, 54, 59, 64, 69, 86, 104, 109, 114, 119, 124, 129, 134, 139, 144, 149, 154, 159, 164, 169, 174, 179, 184, 189}

func (i cipPacketType) String() string {
	if i < 0 || i >= cipPacketType(len(_cipPacketType_index)-1) {
		return fmt.Sprintf("cipPacketType(%d)", i)
	}
	return _cipPacketType_name[_cipPacketType_index[i]:_cipPacketType_index[i+1]]
}
