// generated by stringer -type=cipPacketType; DO NOT EDIT

package main

import "fmt"

const (
	_cipPacketType_name_0 = "PacketSet"
	_cipPacketType_name_1 = "PacketEchoRequestPacketEchoResponse"
)

var (
	_cipPacketType_index_0 = [...]uint8{0, 9}
	_cipPacketType_index_1 = [...]uint8{0, 17, 35}
)

func (i cipPacketType) String() string {
	switch {
	case i == 5:
		return _cipPacketType_name_0
	case 13 <= i && i <= 14:
		i -= 13
		return _cipPacketType_name_1[_cipPacketType_index_1[i]:_cipPacketType_index_1[i+1]]
	default:
		return fmt.Sprintf("cipPacketType(%d)", i)
	}
}
