// generated by stringer -type=Msg; DO NOT EDIT

package icsp

import "fmt"

const _Msg_name = "MsgOnlineConfMsgOnToMsgOffToMsgLevelToMsgStringToMsgCommandToMsgPressFromMsgReleaseFromMsgOnFromMsgOffFromMsgLevelFromMsgStringFromMsgCommandFromMsgPortOnlineMsgLevelUnk1MsgStringLimitMsgCommandLimitMsgLevelTypesMsgDeviceDetailMsgTimeOfDayMsgTODAckMsgPingMsgHeartbeatMsgPong"

var _Msg_map = map[Msg]string{
	1:    _Msg_name[0:13],
	6:    _Msg_name[13:20],
	7:    _Msg_name[20:28],
	10:   _Msg_name[28:38],
	11:   _Msg_name[38:49],
	12:   _Msg_name[49:61],
	132:  _Msg_name[61:73],
	133:  _Msg_name[73:87],
	134:  _Msg_name[87:96],
	135:  _Msg_name[96:106],
	138:  _Msg_name[106:118],
	139:  _Msg_name[118:131],
	140:  _Msg_name[131:145],
	144:  _Msg_name[145:158],
	146:  _Msg_name[158:170],
	147:  _Msg_name[170:184],
	148:  _Msg_name[184:199],
	149:  _Msg_name[199:212],
	151:  _Msg_name[212:227],
	527:  _Msg_name[227:239],
	531:  _Msg_name[239:248],
	1281: _Msg_name[248:255],
	1282: _Msg_name[255:267],
	1409: _Msg_name[267:274],
}

func (i Msg) String() string {
	if str, ok := _Msg_map[i]; ok {
		return str
	}
	return fmt.Sprintf("Msg(%d)", i)
}
