// generated by stringer -type=cipPacketType; DO NOT EDIT

package cip

import "fmt"

const (
	_cipPacketType_name_0 = "packetGreetResponse"
	_cipPacketType_name_1 = "packetSet"
	_cipPacketType_name_2 = "packetEchoRequestpacketEchoResponsepacketGreet"
)

var (
	_cipPacketType_index_0 = [...]uint8{0, 19}
	_cipPacketType_index_1 = [...]uint8{0, 9}
	_cipPacketType_index_2 = [...]uint8{0, 17, 35, 46}
)

func (i cipPacketType) String() string {
	switch {
	case i == 1:
		return _cipPacketType_name_0
	case i == 5:
		return _cipPacketType_name_1
	case 13 <= i && i <= 15:
		i -= 13
		return _cipPacketType_name_2[_cipPacketType_index_2[i]:_cipPacketType_index_2[i+1]]
	default:
		return fmt.Sprintf("cipPacketType(%d)", i)
	}
}
